### PR TITLE
Add Spotless formatting

### PR DESCRIPTION
**Pull request by jjaakola-aiven**
My short study of repositories indicate that there is no formatters applied to source. This is one option to have in builds and enforce in CI.
Don't mind the selected formatting options but having automation would be nice here.

### CODE REVIEW

**Comment by ivanyu** [comment]
@AnatolyPopov you wanted some autoformatter :) Please have a look

**Comment by ivanyu** [comment]
Did you manually change the copyright year or it's Spotless? AFAIK the current consensus is to keep the original year of files

**Comment by jjaakola-aiven** [comment]
@ivanyu Fixed the license header years. Spotless formatted with static year, the `$YEAR` is now used instead of `2022`.
I also removed Checkstyle and added Spotbugs and PMD.

**Review by tvainika — CHANGES_REQUESTED** [review]
conflicts

**Comment by ivanyu** [comment]
let's fix the conflicts and merge

**Review by tvainika — APPROVED** [review]

**Pull request merged**
